<a href="https://colab.research.google.com/github/iamantrikshverma/iamantrikshverma/blob/main/datapreprocessing0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data loading

## import libraries

In [1]:
import pandas as pd

In [2]:
car_data = pd.read_csv("car_price_dataset.csv")

# data checking

## check data

In [3]:
car_data.head()

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
3,Audi,Q5,2023,2.0,Electric,Manual,160971,2,1,11780
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867

In [4]:
car_data.tail()

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884
9996,Chevrolet,Impala,2002,1.4,Electric,Automatic,168000,2,1,6240
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866
9998,Ford,Explorer,2002,1.4,Hybrid,Automatic,225772,4,1,4084
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3,3342

In [5]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         10000 non-null  object
 1   Model         10000 non-null  object
 2   Year          10000 non-null  int64
 3   Engine_Size   10000 non-null  float64
 4   Fuel_Type     10000 non-null  object
 5   Transmission  10000 non-null  object
 6   Mileage       10000 non-null  int64
 7   Doors         10000 non-null  int64
 8   Owner_Count   10000 non-null  int64
 9   Price         10000 non-null  int64
dtypes: float64(1), int64(5), object(4)
memory usage: 781.4+ KB

In [6]:
car_data.describe()

,Year,Engine_Size,Mileage,Doors,Owner_Count,Price
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,2011.543700,3.000560,149239.111800,3.497100,2.991100,8852.96440
std,6.897699,1.149324,86322.348957,1.110097,1.422682,3112.59681
min,2000.000000,1.000000,25.000000,2.000000,1.000000,2000.00000
25%,2006.000000,2.000000,74649.250000,3.000000,2.000000,6646.00000
50%,2012.000000,3.000000,149587.000000,3.000000,3.000000,8858.50000
75%,2017.000000,4.000000,223577.500000,4.000000,4.000000,11086.50000
max,2023.000000,5.000000,299947.000000,5.000000,5.000000,18301.00000

In [7]:
car_data.describe(include="all")

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
count,10000,10000,10000.000000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.00000
unique,10,30,NaN,NaN,4,3,NaN,NaN,NaN,NaN
top,Ford,Accord,NaN,NaN,Electric,Manual,NaN,NaN,NaN,NaN
freq,1048,365,NaN,NaN,2625,3372,NaN,NaN,NaN,NaN
mean,NaN,NaN,2011.543700,3.000560,NaN,NaN,149239.111800,3.497100,2.991100,8852.96440
std,NaN,NaN,6.897699,1.149324,NaN,NaN,86322.348957,1.110097,1.422682,3112.59681
min,NaN,NaN,2000.000000,1.000000,NaN,NaN,25.000000,2.000000,1.000000,2000.00000
25%,NaN,NaN,2006.000000,2.000000,NaN,NaN,74649.250000,3.000000,2.000000,6646.00000
50%,NaN,NaN,2012.000000,3.000000,NaN,NaN,149587.000000,3.000000,3.000000,8858.50000
75%,NaN,NaN,2017.000000,4.000000,NaN,NaN,223577.500000,4.000000,4.000000,11086.50000
max,NaN,NaN,2023.000000,5.000000,NaN,NaN,299947.000000,5.000000,5.000000,18301.00000

## check missing values

In [8]:
# prompt: check missing in car_data

car_data.isnull()

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False

In [10]:
car_data.isnull().sum()

Brand           0
Model           0
Year            0
Engine_Size     0
Fuel_Type       0
Transmission    0
Mileage         0
Doors           0
Owner_Count     0
Price           0
dtype: int64

no missing value found

## outliers/extrema

## IQR method

In [13]:
# prompt: use iqr method on car_data to find outliers

# Calculate Q1, Q3, and IQR for 'mileage'
Q1 = car_data['Mileage'].quantile(0.25)
Q3 = car_data['Mileage'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = car_data[(car_data['Mileage'] < lower_bound) | (car_data['Mileage'] > upper_bound)]

# Print or further process the outliers
print("Outliers in 'Mileage' column using IQR method:")
outliers

Outliers in 'Mileage' column using IQR method:

Empty DataFrame
Columns: [Brand, Model, Year, Engine_Size, Fuel_Type, Transmission, Mileage, Doors, Owner_Count, Price]
Index: []

no outlier data in good state